from sbs_utils.pages.layout.bounds import Bounds
from sbs_utils.pages.layout.column import Column
from sbs_utils.helpers import FrameContext
def merge_props (d):
    ...
def split_props (s, def_key):
    ...
class Button(Column):
    """class Button"""
    def __init__ (self, tag, message) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _pre_present (self, event):
        ...
    def _present (self, event):
        ...
    def update (self, message):
        ...
    @property
    def value (self):
        ...
    @value.setter
    def value (self, v):
        ...
