from sbs_utils.agent import Agent
from sbs_utils.pages.layout.bounds import Bounds
from sbs_utils.pages.layout.clickable import Clickable
from sbs_utils.helpers import FrameContext
class Column(object):
    """class Column"""
    def __init__ (self, left=0, top=0, right=0, bottom=0) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _post_present (self, event):
        ...
    def _pre_present (self, event):
        ...
    def _present (self, event):
        ...
    def calc (self, client_id):
        ...
    def get_cascade_props (self, font=False, color=False, justify=False):
        ...
    def get_color (self):
        ...
    def get_font (self):
        ...
    def get_justify (self):
        ...
    def get_variable (self, default):
        ...
    def invalidate_regions (self):
        ...
    @property
    def is_hidden (self):
        ...
    def on_begin_presenting (self, client_id):
        ...
    def on_end_presenting (self, client_id):
        ...
    def on_message (self, event):
        ...
    def present (self, event):
        ...
    def represent (self, event):
        ...
    def set_border (self, border):
        ...
    def set_bounds (self, bounds) -> None:
        ...
    def set_col_width (self, width):
        ...
    def set_margin (self, margin):
        ...
    def set_padding (self, padding):
        ...
    def set_row_height (self, height):
        ...
    def show (self, _show):
        ...
    def update (self, props):
        ...
    def update_variable (self):
        ...
    @property
    def value (self):
        ...
    @value.setter
    def value (self, a):
        ...
