from sbs_utils.pages.layout.column import Column
from sbs_utils.helpers import FrameContext
class GuiControl(Column):
    """class GuiControl"""
    def __init__ (self, tag, content) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _present (self, event):
        ...
    def invalidate_regions (self):
        ...
    @property
    def is_hidden (self):
        ...
    def on_message (self, event):
        ...
    @property
    def region_tag (self, v):
        ...
    @region_tag.setter
    def region_tag (self, v):
        ...
    def set_bounds (self, bounds) -> None:
        ...
    def update (self, props):
        ...
    @property
    def value (self):
        ...
    @value.setter
    def value (self, v):
        ...
