from sbs_utils.pages.layout.bounds import Bounds
from sbs_utils.pages.layout.clickable import Clickable
from sbs_utils.pages.layout.column import Column
from sbs_utils.helpers import FrameContext
class Row(object):
    """class Row"""
    def __init__ (self, cols=None, width=0, height=0) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _post_present (self, event):
        ...
    def add (self, col):
        ...
    def add_front (self, col):
        ...
    @property
    def bounds (self):
        ...
    def clear (self):
        ...
    @property
    def color (self):
        ...
    @color.setter
    def color (self, v):
        ...
    @property
    def font (self):
        ...
    @font.setter
    def font (self, v):
        ...
    def invalidate_regions (self):
        ...
    @property
    def justify (self):
        ...
    @justify.setter
    def justify (self, v):
        ...
    def on_begin_presenting (self, client_id):
        ...
    def on_end_presenting (self, client_id):
        ...
    def on_message (self, event):
        ...
    def present (self, event):
        ...
    def represent (self, event):
        ...
    def set_border (self, border):
        ...
    def set_col_width (self, width):
        ...
    def set_margin (self, margin):
        ...
    def set_padding (self, padding):
        ...
    def set_row_height (self, height):
        ...
