from sbs_utils.pages.layout.layout import Bounds
from sbs_utils.pages.layout.layout import Column
from sbs_utils.helpers import FrameContext
def get_client_aspect_ratio (cid):
    ...
def get_font_size (font):
    ...
class TextArea(Column):
    """class TextArea"""
    def __init__ (self, tag, message) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _present (self, event):
        ...
    def _present_simple (self, event):
        ...
    def calc (self, client_id):
        ...
    def get_style (self, key):
        ...
    def invalidate_regions (self):
        ...
    def on_message (self, event):
        ...
    def parse_header (self, header):
        ...
    def present (self, event):
        ...
    def update (self, message):
        ...
    @property
    def value (self):
        ...
    @value.setter
    def value (self, message):
        ...
class TextLine(object):
    """class TextLine"""
    def __init__ (self, text, style, width, height, is_sec_end) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
