from sbs_utils.spaceobject import SpaceObject
class DamageDispatcher(object):
    """class DamageDispatcher"""
    def add_source (id: int, cb: callable):
        ...
    def add_target (id: int, cb: callable):
        ...
    def dispatch_damage (sim, damage_event):
        ...
    def remove_source (id: int):
        ...
    def remove_target (id: int):
        ...
