class CollisionDispatcher(object):
    """class CollisionDispatcher"""
    def add_interactive (cb: callable):
        ...
    def add_passive (cb: callable):
        ...
    def dispatch_collision (collision_event):
        ...
    def dispatch_interactive (collision_event):
        ...
    def dispatch_passive (collision_event):
        ...
    def remove_interactive (cb: callable):
        ...
    def remove_passive (cb: callable):
        ...
class DamageDispatcher(object):
    """class DamageDispatcher"""
    def add_any (cb: callable):
        ...
    def add_any_heat (cb: callable):
        ...
    def add_any_internal (cb: callable):
        ...
    def add_any_killed (cb: callable):
        ...
    def add_heat (id: int, cb: callable):
        ...
    def add_internal (id: int, cb: callable):
        ...
    def add_killed (id: int, cb: callable):
        ...
    def add_source (id: int, cb: callable):
        ...
    def add_target (id: int, cb: callable):
        ...
    def dispatch_damage (damage_event):
        ...
    def dispatch_heat (damage_event):
        ...
    def dispatch_internal (damage_event):
        ...
    def dispatch_killed (damage_event):
        ...
    def remove_any (cb: callable):
        ...
    def remove_any_heat (cb: callable):
        ...
    def remove_any_internal (cb: callable):
        ...
    def remove_any_killed (cb: callable):
        ...
    def remove_heat (id: int):
        ...
    def remove_internal (id: int):
        ...
    def remove_killed (id: int):
        ...
    def remove_source (id: int):
        ...
    def remove_target (id: int):
        ...
