class ClientStringDispatcher(object):
    """Low level handler for client strings
    at the Mast level this will dispatch to a promise"""
    def add_any (cb: callable):
        ...
    def dispatch (event):
        ...
    def remove_any (cb: callable):
        ...
class HotkeyDispatcher(object):
    """Low level handler for Hot keys
    at the Mast level this will dispatch to a trigger?"""
    def add_any (cb: callable):
        ...
    def dispatch (event):
        ...
    def remove_any (cb: callable):
        ...
