def get_artemis_audio_dir ():
    ...
def get_artemis_data_dir ():
    ...
def get_artemis_dir ():
    ...
def get_artemis_graphics_dir ():
    ...
def get_mission_dir ():
    ...
def get_mission_dir_filename (filename):
    ...
def get_script_dir ():
    ...
def get_ship_data ():
    ...
def is_dev_build ():
    ...
def load_json_data (file):
    ...
def save_json_data (file, data):
    ...
