def add_to_path (dir):
    ...
def get_artemis_audio_dir ():
    ...
def get_artemis_data_dir ():
    ...
def get_artemis_data_dir_filename (filename):
    ...
def get_artemis_dir ():
    ...
def get_artemis_graphics_dir ():
    ...
def get_mission_audio_file (file):
    ...
def get_mission_dir ():
    ...
def get_mission_dir_filename (filename):
    ...
def get_mission_graphics_file (file):
    ...
def get_mission_name ():
    ...
def get_missions_dir ():
    ...
def get_mod_dir (mod):
    ...
def get_mod_file (mod, file):
    ...
def get_script_dir ():
    ...
def get_startup_mission_name ():
    ...
def is_dev_build ():
    ...
def load_json_data (file):
    ...
def save_json_data (file, data):
    ...
def test_set_exe_dir ():
    ...
