class GridDispatcher(object):
    """class GridDispatcher"""
    def add_object (id: int, cb: callable):
        ...
    def add_point (id: int, cb: callable):
        ...
    def dispatch_grid_event (ctx, event):
        ...
    def remove_object (id: int):
        ...
    def remove_point (id: int):
        ...
