from sbs_utils.agent import Agent
class LaunchDispatcher(object):
    """class LaunchDispatcher"""
    def add_drone (cb: callable):
        ...
    def add_launch (launch_type, cb: callable):
        ...
    def add_missile (cb: callable):
        ...
    def dispatch_drone (event):
        ...
    def dispatch_launch (launch_type, event):
        ...
    def dispatch_missile (event):
        ...
    def remove_drone (cb: callable):
        ...
    def remove_launch (launch_type, cb: callable):
        ...
    def remove_missile (cb: callable):
        ...
