from sbs_utils.agent import Agent
class LifetimeDispatcher(object):
    """class LifetimeDispatcher"""
    def add_destroy (cb: callable):
        ...
    def add_dock (cb: callable):
        ...
    def add_lifecycle (lifecycle, cb: callable):
        ...
    def add_spawn (cb: callable):
        ...
    def add_spawn_grid (cb: callable):
        ...
    def dispatch_damage (damage_event):
        ...
    def dispatch_dock (damage_event):
        ...
    def dispatch_spawn ():
        ...
    def remove_destroy (cb: callable):
        ...
    def remove_dock (cb: callable):
        ...
    def remove_lifecycle (lifecycle, cb: callable):
        ...
    def remove_spawn (cb: callable):
        ...
    def remove_spawn_grid (cb: callable):
        ...
