from sbs_utils.engineobject import EngineObject
class LifetimeDispatcher(object):
    """class LifetimeDispatcher"""
    def add_destroy (cb: callable):
        ...
    def add_spawn (cb: callable):
        ...
    def add_spawn_grid (cb: callable):
        ...
    def dispatch_damage (ctx, damage_event):
        ...
    def dispatch_spawn (ctx):
        ...
    def remove_destroy (cb: callable):
        ...
    def remove_spawn (cb: callable):
        ...
    def remove_spawn_grid (cb: callable):
        ...
