def alien_keys ():
    ...
def arvonian_comms_id (id):
    ...
def arvonian_name (id):
    ...
def arvonian_ship_keys ():
    ...
def arvonian_starbase_keys ():
    ...
def asteroid_keys ():
    ...
def canonical_kralien_comms_id (id, key: str):
    ...
def container_keys ():
    ...
def crystal_asteroid_keys ():
    ...
def danger_keys ():
    ...
def filter_ship_data_by_side (test_key, sides, role=None, ret_key_only=False):
    ...
def get_pool (key):
    ...
def get_ship_data (key):
    ...
def get_ship_name (key):
    ...
def kralien_name (id):
    ...
def kralien_ship (id: int, key: str):
    ...
def kralien_ship_keys ():
    ...
def kralien_starbase_keys ():
    ...
def pirate_ship (v1, v2, v3, of_the):
    ...
def pirate_ship_keys ():
    ...
def pirate_starbase_keys ():
    ...
def plain_asteroid_keys ():
    ...
def random_canonical_kralien_comms_id (id, key: str):
    ...
def random_common_kralien (key: str):
    ...
def random_kralien_name (id):
    ...
def random_pirate_ship ():
    ...
def skaraan_ship_keys ():
    ...
def skaraan_starbase_keys ():
    ...
def terran_ship_keys ():
    ...
def terran_starbase_keys ():
    ...
def torgoth_ship_keys ():
    ...
def torgoth_starbase_keys ():
    ...
def ximni_ship_keys ():
    ...
def ximni_starbase_keys ():
    ...
