def arvonian_comms_id (id):
    ...
def get_pool (key):
    ...
def get_random_npc_call_sign (race):
    ...
def name_arvonian (id):
    ...
def name_canonical_kralien_comms_id (id, key: str):
    ...
def name_kralien (id):
    ...
def name_kralien_ship (id: int, key: str):
    ...
def name_pirate_ship (v1, v2, v3, of_the):
    ...
def name_random_canonical_kralien_comms_id (id, key: str):
    ...
def name_random_common_kralien (key: str):
    ...
def name_random_hostile (race):
    ...
def name_random_kralien (id):
    ...
def name_random_pirate_ship ():
    ...
