from sbs_utils.helpers import FrameContext
def getmembers (object, predicate=None):
    ...
def isfunction (object):
    ...
def mast_print (*args, **kwargs):
    ...
class MastGlobals(object):
    """class MastGlobals"""
    def import_python_function (func, name=None):
        ...
    def import_python_module (mod_name, prepend=None):
        ...
