from sbs_utils.mast.pollresults import PollResults
def mast_runtime_node (parser_node):
    ...
class MastRuntimeNode(object):
    """class MastRuntimeNode"""
    def enter (self, mast, scheduler, node):
        ...
    def leave (self, mast, scheduler, node):
        ...
    def poll (self, mast, scheduler, node):
        ...
