from sbs_utils.mast.core_nodes.decorator_label import DecoratorLabel
def STRING_REGEX_NAMED (name):
    ...
def mast_node (append=True):
    ...
class MapDecoratorLabel(DecoratorLabel):
    """class MapDecoratorLabel"""
    def __init__ (self, path, display_name, if_exp=None, q=None, loc=None, compile_info=None):
        """Initialize self.  See help(type(self)) for accurate signature."""
    def can_fallthrough (self, parent):
        ...
    def generate_label_end_cmds (self, compile_info=None):
        ...
    def parse (lines):
        ...
