from sbs_utils.mast.core_nodes.decorator_label import DecoratorLabel
def STRING_REGEX_NAMED (name):
    ...
def get_artemis_audio_dir ():
    ...
def get_artemis_graphics_dir ():
    ...
def get_mod_dir (mod):
    ...
def get_script_dir ():
    ...
def mast_node (append=True):
    ...
class MediaLabel(DecoratorLabel):
    """class MediaLabel"""
    def __init__ (self, kind, path, display_name, if_exp=None, q=None, loc=None, compile_info=None):
        """Initialize self.  See help(type(self)) for accurate signature."""
    def can_fallthrough (self, parent):
        ...
    def get_of_type (kind, task):
        ...
    def parse (lines):
        ...
    def test (self, task):
        ...
    def test_file (self):
        ...
    def true_path (self):
        ...
