from sbs_utils.engineobject import EngineObject
from sbs_utils.helpers import FrameContext
def _comms_get_origin_id ():
    ...
def _comms_get_selected_id ():
    ...
def comms_broadcast (ids_or_obj, msg, color='#fff'):
    ...
def comms_message (msg, from_ids_or_obj, to_ids_or_obj, title=None, face=None, color='#fff'):
    ...
def comms_receive (msg, title=None, face=None, color='#fff'):
    ...
def comms_receive_internal (msg, ids_or_obj=None, from_name=None, title=None, face=None, color='#fff'):
    ...
def comms_transmit (msg, title=None, face=None, color='#fff'):
    ...
def comms_transmit_internal (msg, ids_or_obj=None, to_name=None, title=None, face=None, color='#fff'):
    ...
def get_inventory_value (so, link, default=None):
    ...
def has_role (so, role):
    ...
