def get_inventory_value (so, link, default=None):
    ...
def gui_add_console_tab (id_or_obj, console, tab_name, label):
    ...
def gui_remove_console_tab (id_or_obj, console, tab_name):
    ...
def set_inventory_value (so, name, value):
    ...
def to_id (other: sbs_utils.engineobject.EngineObject | sbs_utils.engineobject.CloseData | int):
    ...
