from sbs_utils.helpers import FrameContext
from sbs_utils.mast_sbs.story_nodes.media import MediaLabel
def _media_schedule (kind, label, ID=0):
    """Sets the folder from which music is streamed; ID is ship, OR client, OR zero for server.
        """
def get_mission_dir_filename (filename):
    ...
def load_json_data (file):
    ...
def media_read_file (basedir, file):
    ...
def media_read_from_zip (zip_file, file, as_utf8=True):
    ...
def media_read_relative_file (file):
    ...
def media_schedule (kind, name, ID=0):
    """Sets the folder from which music is streamed; ID is ship, OR client, OR zero for server.
    
    
    Args:
        name (_type_): _description_
        ID (_type_): _description_"""
def media_schedule_random (kind, ID=0):
    ...
def music_schedule (name, ID=0):
    ...
def music_schedule_random (ID=0):
    ...
def skybox_schedule (name, ID=0):
    ...
def skybox_schedule_random (ID=0):
    ...
def sub_task_schedule (*args, **kwargs):
    ...
