from sbs_utils.futures import PromiseAllAny
def awaitable (func):
    ...
def prefab_autoname (name):
    ...
def prefab_spawn (*args, **kwargs):
    ...
def task_schedule (*args, **kwargs):
    ...
class PrefabAll(PromiseAllAny):
    """class PrefabAll"""
    def __init__ (self, proms) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def result (self):
        ...
