from sbs_utils.engineobject import EngineObject
from sbs_utils.helpers import FrameContext
def get_inventory_value (so, link, default=None):
    ...
def has_role (so, role):
    ...
def science_set_scan_data (player_id_or_obj, scan_target_id_or_obj, tab, message):
    ...
def science_start_scan (origin_id, selected_id, tab):
    ...
