def get_mission_dir_filename (filename):
    ...
def load_json_data (file):
    ...
def load_yaml_data (file):
    ...
def settings_add_defaults (additions):
    ...
def settings_get_defaults ():
    ...
