def alien_keys ():
    ...
def arvonian_ship_keys ():
    ...
def arvonian_starbase_keys ():
    ...
def asteroid_keys ():
    ...
def container_keys ():
    ...
def crystal_asteroid_keys ():
    ...
def danger_keys ():
    ...
def filter_ship_data_by_side (test_key, sides, role=None, ret_key_only=False):
    ...
def get_artemis_data_dir ():
    ...
def get_mission_dir ():
    ...
def get_mod_dir (mod):
    ...
def get_ship_data ():
    ...
def get_ship_data_for (key):
    ...
def get_ship_index ():
    ...
def get_ship_name (key):
    ...
def kralien_ship_keys ():
    ...
def kralien_starbase_keys ():
    ...
def load_json_data (file):
    ...
def merge_mod_ship_data (mod):
    ...
def pirate_ship_keys ():
    ...
def pirate_starbase_keys ():
    ...
def plain_asteroid_keys ():
    ...
def reset_ship_data_caches ():
    ...
def skaraan_ship_keys ():
    ...
def skaraan_starbase_keys ():
    ...
def terran_ship_keys ():
    ...
def terran_starbase_keys ():
    ...
def torgoth_ship_keys ():
    ...
def torgoth_starbase_keys ():
    ...
def ximni_ship_keys ():
    ...
def ximni_starbase_keys ():
    ...
