from sbs_utils.gridobject import GridObject
from sbs_utils.objects import Npc
from sbs_utils.objects import PlayerShip
from sbs_utils.objects import Terrain
def grid_spawn (id, name, tag, x, y, icon, color, roles):
    ...
def npc_spawn (x, y, z, name, side, art_id, behave_id):
    ...
def player_spawn (x, y, z, name, side, art_id):
    ...
def terrain_spawn (x, y, z, name, side, art_id, behave_id):
    ...
