from sbs_utils.helpers import FrameContext
def clear_counter (id_or_obj, name):
    ...
def clear_timer (id_or_obj, name):
    ...
def format_time_remaining (id_or_obj, name):
    ...
def get_counter_elapsed_seconds (id_or_obj, name):
    ...
def get_inventory_value (so, link, default=None):
    ...
def get_time_remaining (id_or_obj, name):
    ...
def is_timer_finished (id_or_obj, name):
    ...
def is_timer_set (id_or_obj, name):
    ...
def is_timer_set_and_finished (id_or_obj, name):
    ...
def set_inventory_value (so, name, value):
    ...
def set_timer (id_or_obj, name, seconds=0, minutes=0):
    ...
def start_counter (id_or_obj, name):
    ...
