from sbs_utils.consoledispatcher import ConsoleDispatcher
from sbs_utils.engineobject import EngineObject
from sbs_utils.pymast.pollresults import PollResults
def receive (text, origin_id, selected_id, color=None, face=None, title=None):
    ...
def transmit (text, origin_id, selected_id, color=None, face=None, title=None):
    ...
class PyMastComms(object):
    """class PyMastComms"""
    def __init__ (self, task, buttons, origin_id, selected_id) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def broadcast (id, text, color=None):
        ...
    def clear (self):
        ...
    def get_origin (self):
        ...
    def get_selected (self):
        ...
    def handled_selected (self, origin_id, selected_id):
        ...
    def message (self, sim, message, player_id, event):
        ...
    def receive (self, text, color=None, face=None, title=None):
        ...
    def run (self):
        ...
    def selected (self, sim, _, event):
        ...
    def selected_info (self, origin_id, selected_id):
        ...
    def stop (self):
        ...
    def transmit (self, text, color=None, face=None, title=None):
        ...
