from sbs_utils.mast.core_nodes.label import Label
def mast_node (append=True):
    ...
class DecoratorLabel(Label):
    """class DecoratorLabel"""
    def __init__ (self, name, loc=None):
        """Initialize self.  See help(type(self)) for accurate signature."""
    def can_fallthrough (self, parent):
        ...
    def generate_label_begin_cmds (self, compile_info=None):
        ...
    def generate_label_end_cmds (self, compile_info=None):
        ...
    def next_label_id ():
        ...
    def parse (lines):
        ...
