from sbs_utils.agent import Agent
from sbs_utils.mast.mast_node import DescribableNode
def get_story_id ():
    ...
def mast_node (append=True):
    ...
class Label(DescribableNode, Agent):
    """class Label"""
    def __init__ (self, name, replace=None, m=None, loc=None, compile_info=None):
        """Initialize self.  See help(type(self)) for accurate signature."""
    def _add (id, obj):
        ...
    def _remove (id):
        ...
    def add_child (self, cmd):
        ...
    def add_label (self, name, label):
        ...
    def add_option (self, prefix, text):
        ...
    def append_text (self, prefix, text):
        ...
    def apply_metadata (self, data):
        ...
    def can_fall_into (self, parent):
        ...
    def can_fallthrough (self, parent):
        ...
    def clear ():
        ...
    @property
    def desc (self):
        ...
    def generate_label_begin_cmds (self, compile_info=None):
        ...
    def generate_label_end_cmds (self, compile_info=None):
        ...
    def get (id):
        ...
    def get_as (id, as_cls):
        ...
    def get_objects_from_set (the_set):
        ...
    def get_role_object (link_name):
        ...
    def get_role_objects (role):
        ...
    def get_role_set (role):
        ...
    def has_inventory_list (collection_name):
        ...
    def has_inventory_set (collection_name):
        ...
    def has_links_list (collection_name):
        ...
    def has_links_set (collection_name):
        ...
    def parse (lines):
        ...
    def remove_id (id):
        ...
    def resolve_id (other: 'Agent | CloseData | int'):
        ...
    def resolve_py_object (other: 'Agent | CloseData | int'):
        ...
