from sbs_utils.helpers import FrameContext
from sbs_utils.pages.widgets.layout_listbox import LayoutListbox
def apply_control_styles (control_name, extra_style, layout_item, task):
    ...
def gui_list_box (items, style, item_template=None, title_template=None, section_style=None, title_section_style=None, select=False, multi=False, carousel=False, collapsible=False, read_only=False):
    ...
